### ISSUE TITLE
undefined is not a function after ember-cli 2.9.1 upgrade

### ISSUE THREAD

**Issue by robj** [adopted-ember-addons/ember-notify#101]
using ember-notify 5.1.6

```
undefined is not a function
TypeError: undefined is not a function
    at Class.module.exports.included (/Users/robert/dev/stud-ember/node_modules/ember-notify/index.js:8:26)
    at Class.superWrapper [as included] (/Users/robert/dev/stud-ember/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at EmberApp.<anonymous> (/Users/robert/dev/stud-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:470:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Users/robert/dev/stud-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:465:45)
    at new EmberApp (/Users/robert/dev/stud-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:138:8)
    at module.exports (/Users/robert/dev/stud-ember/ember-cli-build.js:31:15)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/Users/robert/dev/stud-ember/node_modules/ember-cli/lib/models/builder.js:70:19)
    at CoreObject.module.exports.Task.extend.init (/Users/robert/dev/stud-ember/node_modules/ember-cli/lib/models/builder.js:50:10)
    at CoreObject.superWrapper [as init] (/Users/robert/dev/stud-ember/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
```

**Comment by robj** [comment]
The problem was Object.assign, downgrading to ember-notify v5.1.5, and adding the object-assign dependency resolved this for me

**Comment by aexmachina** [comment]
Okay thanks. Have pushed v5.1.7 with a polyfill for this.

**Comment by btecu** [comment]
Closing this as solved.
