### ISSUE TITLE
6.0.2: _runloop.run.later is not a function

### ISSUE THREAD

**Issue by abueloshika** [adopted-ember-addons/ember-notify#181]
I recently updated to Ember 4.1.1 and Ember Notify 6.0.2. Since the update I get the following an error when a Notify element tries to close:

```
Uncaught (in promise) TypeError: _runloop.run.later is not a function
    at Class.didInsertElement (message.js:50:1)
    at Class.superWrapper [as didInsertElement] (index.js:429:1)
    at Class.trigger (core_view.js:68:1)
    at Class.superWrapper [as trigger] (index.js:429:1)
    at CurlyComponentManager.didCreate (index.js:2420:1)
    at TransactionImpl.commit (runtime.js:4759:1)
    at EnvironmentImpl.commit (runtime.js:4883:1)
    at inTransaction (runtime.js:4908:1)
    at Renderer._renderRoots (index.js:6220:1)
    at Renderer._renderRootsTransaction (index.js:6272:1)
```

and the element just hangs around on the UI. The error occurs with or without a `closeAfter` argument.

**Comment by gzurbach** [comment]
I just opened a PR to fix this deprecation warning and allow usage with Ember 4. 

Note : I am not sure if it's all backward compatible (as in: when was `later` exported from the package).
